config/routes.rb
Rails.application.routes.draw do
resources :users


resource :session
resources :subs, except: [:destroy] do
  resources :posts, only: [:show, :new, :create]
end

resources :posts, except: [:index, :destroy, :show, :new, :create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_subs

  has_many(
    :subs,
    through: :post_subs,
    source: :sub

  )
  belongs_to(
    :author,
    class_name: :User,
    foreign_key: :author_id
  )
end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates_uniqueness_of :post_id, scope: [:sub_id]
  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  belongs_to(
    :moderator,
    class_name: :User,
    foreign_key: :moderator_id
  )

  has_many :post_subs
  has_many :posts, through: :post_subs, source: :post
  validates :title, :description, :moderator_id, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many(
    :subs,
    class_name: :Sub,
    foreign_key: :moderator_id,
    dependent: :destroy
  )

  has_many(
    :posts,
    class_name: :Post,
    foreign_key: :author_id,
    dependent: :destroy
  )

  attr_reader :password
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    @user && @user.is_password?(password) ? @user : nil
  end

  def generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token
    self.session_token = generate_session_token
    self.save!
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :user_params

  def login(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :is_author, only:[:edit, :update]

  def new
    @post = Post.new
    @sub = Sub.find(params[:sub_id])
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      params[:post][:sub_ids].each do |id|
        PostSub.new(sub_id: id, post_id: @post.id).save
      end
      redirect_to sub_post_url(params['sub_id'], @post.id)
    else
      render :new
    end
  end

  def edit

    @post = Post.find(params[:id])
    @subs = Sub.all
    @post_subs = @post.post_subs.map {|post| post.sub_id }
  end

  def update

    @post = Post.find(params[:id])
    #@post_subs = PostSub.find_by(post_id: params[:id]).select(:sub_id <> params)

    @post.author_id =current_user.id
    fail
    if @post.update(post_params)
      redirect_to subs_url
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])

  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #@user = User.new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Can't login"]
      render :new
    end

  end

  def destroy

    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :edit_update_sub, only: [:edit, :update]
  before_action :validate_user, except: [:show, :index]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = ["Did not create sub"]
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = ["Did not update sub"]
      render :edit
    end
  end


  def show
    @sub = Sub.find(params[:id])

    @posts = @sub.posts
  end

  def index
    @subs = Sub.all
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

  def edit_update_sub
    @sub = Sub.find(params[:id])
    unless current_user.id == @sub.moderator_id
      [:error] << "Wrong User"
    end
  end

  def validate_user
    unless session[:session_token]
      flash.now[:error] = ["Not Logged In"]
      redirect_to new_session_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "Invalid Username/Password Combination"
      render :new
    end

  end

  def show
    if current_user.nil?
      redirect_to new_session_url
      return
    end
    @user = current_user
    render :show
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "Failed to update user"
      render :edit
    end
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<%= current_user.username%>
<%= button_to "Sign Out", session_url, method: :delete %>
<%else%>
<%= button_to "Sign In", new_session_url, method: :get %>
<%= button_to "Create User", new_user_url, method: :get %>
<%end%>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_show.html.erb
<% @posts.each do |post| %>
  <p>PostId: <%=post.id%></p>

  <%= link_to "#{post.title}", sub_post_url(sub_id, post.id)%>
  <br>
  <br>
  <%=post.url%>
  <br>
  <%=post.content%>
<%end%>

app/views/posts/edit.html.erb
<h1>Edit this post<h1>
  <form action=<%=post_url(@post)%> method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <label for="title">Title</label>
    <input type="text" name="post[title]" id = "title" value="<%= @post.title %>">
    <br>

    <label for="url">Link</label>
    <input type="text" name="post[url]" id = "url" value="<%= @post.url %>">
    <br>

    <input type="hidden" name="post[sub_ids][]" value="">
    <% @subs.each do |sub| %>
      <label for="<%= sub.title %>"><%= sub.title %></label>

      <input type = "checkbox" name = "post[sub_ids][]" value = "<%= sub.id %>" id="<%= sub.title %>"
        <% if @post_subs.include?(sub.id) %>
          checked
        <% end %>
        >
      <br>
    <% end %>

    <label for="content">Content</label>
    <input type="textarea" name="post[content]" id = "content" value="<%= @post.content %>">

    <input type="submit" value="Update Post">
  </form>

app/views/posts/new.html.erb
<h1>Create a post<h1>
  <form action="<%=sub_posts_url(@sub)%>" method = "post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="title">Title</label>
    <input type="text" name="post[title]" id = "title">
    <br>
    <label for="url">Link</label>
    <input type="text" name="post[url]" id = "url">
    <br>

    <% @subs.each do |sub| %>
      <label for="<%= sub.title %>"><%= sub.title %></label>

      <input type = "checkbox" name = "post[sub_ids][]" value = "<%= sub.id %>" id="<%= sub.title %>">
      <br>
    <% end %>

    <label for="content">Content</label>
    <input type="textarea" name="post[content]" id = "content">
    <input type="submit" value="Submit Post">
  </form>

app/views/posts/show.html.erb
<p>PostId: <%=@post.id%></p>
<%=@post.title%>
<br>
<%=@post.url%>
<br>
<%=@post.content%>
<br>
<%= link_to "Edit post", edit_post_url(@post) %>
<br>

app/views/subs/edit.html.erb
<h1>Edit this sub<h1>
  <form action="<%=sub_url(@sub)%>" method = "post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="title">Title</label>
    <input type="text" name="sub[title]" id = "title">
    <br>
    <label for="description">Description</label>
    <input type="text" name="sub[description]" id = "description">
    <input type="submit" value="Submit Sub">
  </form>

app/views/subs/index.html.erb
<h1>List of subs</h1>
<% @subs.each do |sub| %>
  <%= link_to "#{sub.title}", sub_url(sub) %>
  <br>
<% end %>

app/views/subs/new.html.erb
<h1>Create a sub<h1>
  <form action="<%=subs_url(@sub)%>" method = "post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="title">Title</label>
    <input type="text" name="sub[title]" id = "title">
    <br>
    <label for="description">Description</label>
    <input type="text" name="sub[description]" id = "description">
    <input type="submit" value="Submit Sub">
  </form>

app/views/subs/show.html.erb
<h1>Sub Page </h1>
<%= @sub.title %>
<%=button_to "Edit Sub", edit_sub_url, method: :get %>
<%=button_to "Make new post", new_sub_post_url(@sub), method: :get %>

<%= render 'posts/show', post: @posts, sub_id: @sub.id %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<form action="<%=user_url(@user)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <input type="hidden" name="_method" value="patch">
  <label for="username">Username</label>
  <input type="text" name="user[username]" value="<%@user.username%>" id = "username">
  <br>
  <label for="password">Password</label>
  <input type="password" name="user[password]" id = "password">
  <input type="submit" value="Change user">
</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%=users_url%>" method = "post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="username">Username</label>
  <input type="text" name="user[username]" value="<%=@user.username%>" id = "username">
  <br>
  <label for="password">Password</label>
  <input type="password" name="user[password]" id = "password">
  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<%=@user.username %>